### ISSUE TITLE
ESPN3 events in main appletv menu are giving 403 forbidden error

### ISSUE THREAD

**Issue by siuside** [awaters1/plugin.video.espn_3#12]
` ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 403: Forbidden
                                            Traceback (most recent call last):
                                              File "C:\Users\htpc\AppData\Roaming\Kodi\addons\plugin.video.espn_3\addon.py", line 864, in <module>
                                                PLAY_TV(args)
                                              File "C:\Users\htpc\AppData\Roaming\Kodi\addons\plugin.video.espn_3\addon.py", line 729, in PLAY_TV
                                                session_json = util.get_url_as_json(start_session_url)
                                              File "C:\Users\htpc\AppData\Roaming\Kodi\addons\plugin.video.espn_3\util.py", line 60, in get_url_as_json
                                                response = urllib2.urlopen(url)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 127, in urlopen
                                                return _opener.open(url, data, timeout)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 410, in open
                                                response = meth(req, response)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 523, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 448, in error
                                                return self._call_chain(*args)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 382, in _call_chain
                                                result = func(*args)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 531, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 403: Forbidden`

Don't remember if I checked this before cleared cached data, but after I cleared cache, authorization information was retained but ESPN3 in new menu doesn't work. Navigating to old style menu, I am still able to play ESPN3 events there however, so that is good. 

I restored saved data after clearing cache to reinstate old files and still get ESPN3 403 error on the main screen. Works fine in old style menu ESPN3

Edit: After posts in the forum thread, this appears to be happening after clearing cached data...

**Comment by awaters1** [comment]
Next time it happens can you get the url from the log that says  something like 'ESPN3: start_session_url' copy that URL, paste it into the browser, and then copy the contents here.  I don't think it contains anything personal.

**Comment by siuside** [comment]
Unable to duplicate after https://github.com/awaters1/plugin.video.espn_3/commit/bfe2bece1d8316a7504a85900140ea3d099f44fb . Tried clearing cache and without clearing cache as well. We should close this.

**Comment by siuside** [comment]
Ok I am able to replicate this

`14:16:57 T:10260  NOTICE: ESPN3: args {'EVENT_ID': ['361451086'], 'MODE': ['PLAY_TV'], 'EVENT_NAME': ['Georgia Tech vs. Boston College (First Round) (ACC Baseball Championship)'], 'EVENT_PARENTAL_RATING': ['G'], 'NETWORK_NAME': ['espn3'], 'EVENT_GUID': ['espn3/Georgia Tech vs. Boston College (First Round) (ACC Baseball Championship)/2811490'], 'SESSION_URL': ['https://broadband.espn.go.com/espn3/auth/watchespn/startSession?channel=espn3&simulcastAiringId=118925611']}
14:16:57 T:10260  NOTICE: ESPN3 util: Using cache http://broadband.espn.go.com/espn3/auth/watchespn/userData?format=json for C:\Users\htpc\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.espn_3\user_data.json
14:16:57 T:10260  NOTICE: ESPN3: User needs login to ESPN3
14:16:57 T:10260  NOTICE: ESPN3-adobe-api: already authorized
14:16:58 T:10260  NOTICE: ESPN3: start_session_url: https://broadband.espn.go.com/espn3/auth/watchespn/startSession?channel=espn3&simulcastAiringId=118925611&playbackScenario=HTTP_CLOUD_HIGH&resource=PHJzcyB2ZXJzaW9uPSIyLjAiIHhtbG5zOm1lZGlhPSJodHRwOi8vc2VhcmNoLnlhaG9vLmNvbS9tcnNzLyI%2BPGNoYW5uZWw%2BPHRpdGxlPjwhW0NEQVRBW2VzcG4zXV0%2BPC90aXRsZT48aXRlbT48dGl0bGU%2BPCFbQ0RBVEFbR2VvcmdpYSBUZWNoIHZzLiBCb3N0b24gQ29sbGVnZSAoRmlyc3QgUm91bmQpIChBQ0MgQmFzZWJhbGwgQ2hhbXBpb25zaGlwKV1dPjwvdGl0bGU%2BPGd1aWQ%2BPCFbQ0RBVEFbZXNwbjMvR2VvcmdpYSBUZWNoIHZzLiBCb3N0b24gQ29sbGVnZSAoRmlyc3QgUm91bmQpIChBQ0MgQmFzZWJhbGwgQ2hhbXBpb25zaGlwKS8yODExNDkwXV0%2BPC9ndWlkPjxtZWRpYTpyYXRpbmcgc2NoZW1lPSJ1cm46di1jaGlwIj48IVtDREFUQVtHXV0%2BPC9tZWRpYTpyYXRpbmc%2BPC9pdGVtPjwvY2hhbm5lbD48L3Jzcz4%3D&tokenType=ADOBEPASS&platform=tvos&token=PHNpZ25hdHVyZUluZm8%2BQzl5QUVwZW1nSFlNTVZPSFY2K2ttSW1Ic3hmc3ZBeVI1LzZOazlyN0NlUFI2U0NmQzZoZGJReENEa2g4UFBmdEQ1MmhhYUM1OUtyZFBDZllYZk9FYzNseFpRWGFSRVlUZlVGZEl6SEI3SnQ2VjMyUnovV3laRWExQU9WSHcweDVGQmRjQytPQmZWVysvT2NHc1NPWDNRclEvMndzeVNyamJlQm1FMWtvblVJPTxzaWduYXR1cmVJbmZvPjxhdXRoVG9rZW4%2BPHNlc3Npb25HVUlEPjlkYzcxMjA1Njg4OGM0N2RhNDZjOTNiMGI5OGNjY2M0PC9zZXNzaW9uR1VJRD48cmVxdWVzdG9ySUQ%2BRVNQTjwvcmVxdWVzdG9ySUQ%2BPHJlc291cmNlSUQ%2BPCFbQ0RBVEFbPHJzcyB2ZXJzaW9uPSIyLjAiIHhtbG5zOm1lZGlhPSJodHRwOi8vc2VhcmNoLnlhaG9vLmNvbS9tcnNzLyI%2BPGNoYW5uZWw%2BPHRpdGxlPjwhW0NEQVRBW2VzcG4zXV1dXT4%2BPCFbQ0RBVEFbPC90aXRsZT48aXRlbT48dGl0bGU%2BPCFbQ0RBVEFbR2VvcmdpYSBUZWNoIHZzLiBCb3N0b24gQ29sbGVnZSAoRmlyc3QgUm91bmQpIChBQ0MgQmFzZWJhbGwgQ2hhbXBpb25zaGlwKV1dXV0%2BPjwhW0NEQVRBWzwvdGl0bGU%2BPGd1aWQ%2BPCFbQ0RBVEFbZXNwbjMvR2VvcmdpYSBUZWNoIHZzLiBCb3N0b24gQ29sbGVnZSAoRmlyc3QgUm91bmQpIChBQ0MgQmFzZWJhbGwgQ2hhbXBpb25zaGlwKS8yODExNDkwXV1dXT4%2BPCFbQ0RBVEFbPC9ndWlkPjxtZWRpYTpyYXRpbmcgc2NoZW1lPSJ1cm46di1jaGlwIj48IVtDREFUQVtHXV1dXT4%2BPCFbQ0RBVEFbPC9tZWRpYTpyYXRpbmc%2BPC9pdGVtPjwvY2hhbm5lbD48L3Jzcz5dXT48L3Jlc291cmNlSUQ%2BPHR0bD40MjAwMDA8L3R0bD48aXNzdWVUaW1lPjIwMTYtMDUtMjQgMTI6MTY6NDYgLTA3MDA8L2lzc3VlVGltZT48bXZwZElkPlRXQzwvbXZwZElkPjwvYXV0aFRva2VuPg%3D%3D&v=2.0.0&partner=watchespn
14:16:58 T:10260   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 403: Forbidden
                                            Traceback (most recent call last):
                                              File "C:\Users\htpc\AppData\Roaming\Kodi\addons\plugin.video.espn_3\addon.py", line 785, in <module>
                                                PLAY_TV(args)
                                              File "C:\Users\htpc\AppData\Roaming\Kodi\addons\plugin.video.espn_3\addon.py", line 640, in PLAY_TV
                                                session_json = util.get_url_as_json(start_session_url)
                                              File "C:\Users\htpc\AppData\Roaming\Kodi\addons\plugin.video.espn_3\util.py", line 62, in get_url_as_json
                                                response = urllib2.urlopen(url)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 127, in urlopen
                                                return _opener.open(url, data, timeout)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 410, in open
                                                response = meth(req, response)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 523, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 448, in error
                                                return self._call_chain(*args)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 382, in _call_chain
                                                result = func(*args)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 531, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 403: Forbidden
                                            -->End of Python script error report<--
14:16:58 T:2704   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.espn_3/?EVENT_PARENTAL_RATING=G&EVENT_ID=361451086&EVENT_NAME=Georgia+Tech+vs.+Boston+College+%28First+Round%29+%28ACC+Baseball+Championship%29&SESSION_URL=https%3A%2F%2Fbroadband.espn.go.com%2Fespn3%2Fauth%2Fwatchespn%2FstartSession%3Fchannel%3Despn3%26simulcastAiringId%3D118925611&NETWORK_NAME=espn3&EVENT_GUID=espn3%2FGeorgia+Tech+vs.+Boston+College+%28First+Round%29+%28ACC+Baseball+Championship%29%2F2811490&MODE=PLAY_TV]`


and here is the relevant snippet when I go to the session URL 

`<auth-status>
<successStatus/>
</auth-status>
<blackout-status>
<errorCode>BLACKOUT</errorCode>
<errorMessage>This event has been blacked out in your area.</errorMessage>
</blackout-status>`

Perhaps we should display this error instead of the default error message to check the logs?

**Comment by awaters1** [comment]
The session url should have returned JSON not XML. Either way it is due to a blackout I believe because it says "Georgia Tech vs. Boston College (First Round) (ACC Baseball Championship) Closed captioning available
(subject to blackout)" on the espn schedule.

Through which menu system did you reach this ESPN3 event? I think with the appletv the blackouts are defined when the event is listed.

**Comment by siuside** [comment]
It was through the main menu/appletv menu. I forgot to try the same event via legacy menu.

It was definitely due to blackout. I tested with proxy settings to enforce blackout and work around the blackout

**Comment by awaters1** [comment]
Ok thanks, next time it happens can you go to http://espn.go.com/watchespn/appletv/featured and save that XML file? That lists the events for ESPN3 in the appletv menu.  I think that is were the blackout settings show up.

**Comment by siuside** [comment]
Sure, will keep an eye on that.

**Comment by awaters1** [comment]
I was able to find one, I'll work on integrating it.

**Comment by awaters1** [comment]
Should be fixed with 215695ef72d80112cb5741a6ba635a10e794e639 there are not too many blackouts in my area so it will be tedious for me to test this with live content.

**Comment by siuside** [comment]
They primarily block the east coast regions for ESPN3 and MLB local games on the main networks. We should be able to track in the next few days.

**Comment by siuside** [comment]
Almost there. Event is Miami vs NC State Baseball. I think the ACC events are more prone to blackouts for their local regions and my proxy is based out of there, so this is easy to test.

1) In the "ESPN3" main appletv menu, "Channels -> ESPN3" menu, "Sports -> Baseball -> Live and Upcoming" menu all displaying BLACKOUT correctly. 

[https://imgur.com/Kqldus8](url)


2) When I access the session_url in browser

<blackout-status>
<errorCode>BLACKOUT</errorCode>
<errorMessage>This event has been blacked out in your area.</errorMessage>
</blackout-status>

3) In Kodi logs

`18:55:15 T:4612   ERROR: Previous line repeats 6 times.
18:55:15 T:4612  NOTICE: ESPN3: args {'EVENT_ID': ['361471095'], 'MODE': ['PLAY_TV'], 'EVENT_NAME': ['#4 Miami (FL) vs. #14 North Carolina State (Pool Play Round) (ACC Baseball Championship)'], 'EVENT_PARENTAL_RATING': ['G'], 'NETWORK_NAME': ['espn3'], 'EVENT_GUID': ['espn3/#4 Miami (FL) vs. #14 North Carolina State (Pool Play Round) (ACC Baseball Championship)/2811554'], 'SESSION_URL': ['https://broadband.espn.go.com/espn3/auth/watchespn/startSession?channel=espn3&simulcastAiringId=118925617']}
18:55:15 T:4612  NOTICE: ESPN3 util: Using cache http://broadband.espn.go.com/espn3/auth/watchespn/userData?format=json for C:\Users\htpc\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.espn_3\user_data.json
18:55:15 T:4612  NOTICE: ESPN3: User needs login to ESPN3
18:55:17 T:4612  NOTICE: ESPN3: start_session_url: https://broadband.espn.go.com/espn3/auth/watchespn/startSession?channel=espn3&simulcastAiringId=118925617&playbackScenario=HTTP_CLOUD_HIGH&resource=PHJzcyB2ZXJzaW9uPSIyLjAiIHhtbG5zOm1lZGlhPSJodHRwOi8vc2VhcmNoLnlhaG9vLmNvbS9tcnNzLyI%2BPGNoYW5uZWw%2BPHRpdGxlPjwhW0NEQVRBW2VzcG4zXV0%2BPC90aXRsZT48aXRlbT48dGl0bGU%2BPCFbQ0RBVEFbIzQgTWlhbWkgKEZMKSB2cy4gIzE0IE5vcnRoIENhcm9saW5hIFN0YXRlIChQb29sIFBsYXkgUm91bmQpIChBQ0MgQmFzZWJhbGwgQ2hhbXBpb25zaGlwKV1dPjwvdGl0bGU%2BPGd1aWQ%2BPCFbQ0RBVEFbZXNwbjMvIzQgTWlhbWkgKEZMKSB2cy4gIzE0IE5vcnRoIENhcm9saW5hIFN0YXRlIChQb29sIFBsYXkgUm91bmQpIChBQ0MgQmFzZWJhbGwgQ2hhbXBpb25zaGlwKS8yODExNTU0XV0%2BPC9ndWlkPjxtZWRpYTpyYXRpbmcgc2NoZW1lPSJ1cm46di1jaGlwIj48IVtDREFUQVtHXV0%2BPC9tZWRpYTpyYXRpbmc%2BPC9pdGVtPjwvY2hhbm5lbD48L3Jzcz4%3D&tokenType=ADOBEPASS&platform=tvos&token=PHNpZ25hdHVyZUluZm8%2BcjdCa1RCc1U0aXQyYWp3a2RmajAwNVNFSkpMZVdESk16bHBJTHFjSHpoa0xDR0dXK25MY2ZDTEdTRnFKVzB5bDJKcU9HSW41d0hXNVlrYkNtaGNWN0tQS0ZER3ZEejRqMzRmZTNBdkhQQW9oVmhHcU02aE5VVVJsWmpiUzdEb21JY1drTS9NM0pud3ZIUEhvWjNsamtMRkxxSGhlVGdCYWVvUTFSOTR6cXVJPTxzaWduYXR1cmVJbmZvPjxhdXRoVG9rZW4%2BPHNlc3Npb25HVUlEPjlkYzcxMjA1Njg4OGM0N2RhNDZjOTNiMGI5OGNjY2M0PC9zZXNzaW9uR1VJRD48cmVxdWVzdG9ySUQ%2BRVNQTjwvcmVxdWVzdG9ySUQ%2BPHJlc291cmNlSUQ%2BPCFbQ0RBVEFbPHJzcyB2ZXJzaW9uPSIyLjAiIHhtbG5zOm1lZGlhPSJodHRwOi8vc2VhcmNoLnlhaG9vLmNvbS9tcnNzLyI%2BPGNoYW5uZWw%2BPHRpdGxlPjwhW0NEQVRBW2VzcG4zXV1dXT4%2BPCFbQ0RBVEFbPC90aXRsZT48aXRlbT48dGl0bGU%2BPCFbQ0RBVEFbIzQgTWlhbWkgKEZMKSB2cy4gIzE0IE5vcnRoIENhcm9saW5hIFN0YXRlIChQb29sIFBsYXkgUm91bmQpIChBQ0MgQmFzZWJhbGwgQ2hhbXBpb25zaGlwKV1dXV0%2BPjwhW0NEQVRBWzwvdGl0bGU%2BPGd1aWQ%2BPCFbQ0RBVEFbZXNwbjMvIzQgTWlhbWkgKEZMKSB2cy4gIzE0IE5vcnRoIENhcm9saW5hIFN0YXRlIChQb29sIFBsYXkgUm91bmQpIChBQ0MgQmFzZWJhbGwgQ2hhbXBpb25zaGlwKS8yODExNTU0XV1dXT4%2BPCFbQ0RBVEFbPC9ndWlkPjxtZWRpYTpyYXRpbmcgc2NoZW1lPSJ1cm46di1jaGlwIj48IVtDREFUQVtHXV1dXT4%2BPCFbQ0RBVEFbPC9tZWRpYTpyYXRpbmc%2BPC9pdGVtPjwvY2hhbm5lbD48L3Jzcz5dXT48L3Jlc291cmNlSUQ%2BPHR0bD40MjAwMDA8L3R0bD48aXNzdWVUaW1lPjIwMTYtMDUtMjYgMTY6NTU6MzUgLTA3MDA8L2lzc3VlVGltZT48bXZwZElkPlRXQzwvbXZwZElkPjwvYXV0aFRva2VuPg%3D%3D&v=2.0.0&partner=watchespn
18:55:17 T:4612   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 403: Forbidden
                                            Traceback (most recent call last):
                                              File "C:\Users\htpc\AppData\Roaming\Kodi\addons\plugin.video.espn_3\addon.py", line 789, in <module>
                                                PLAY_TV(args)
                                              File "C:\Users\htpc\AppData\Roaming\Kodi\addons\plugin.video.espn_3\addon.py", line 641, in PLAY_TV
                                                session_json = util.get_url_as_json(start_session_url)
                                              File "C:\Users\htpc\AppData\Roaming\Kodi\addons\plugin.video.espn_3\util.py", line 63, in get_url_as_json
                                                response = urllib2.urlopen(url)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 127, in urlopen
                                                return _opener.open(url, data, timeout)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 410, in open
                                                response = meth(req, response)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 523, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 448, in error
                                                return self._call_chain(*args)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 382, in _call_chain
                                                result = func(*args)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 531, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 403: Forbidden
                                            -->End of Python script error report<--
`

**Only place it is missing is the Old Style Menu**

[https://imgur.com/fUY1HJJ](url)

**Comment by awaters1** [comment]
The legacy menu's data source doesn't have access to the blackout information when listing the events, I added a check for legacy items when they play in 19a222c16ba97c71813f3387cd62e0d172ff65fd

**Comment by siuside** [comment]
Still doesn't display BLACKOUT in the legacy menu with https://github.com/awaters1/plugin.video.espn_3/commit/19a222c16ba97c71813f3387cd62e0d172ff65fd

**Comment by awaters1** [comment]
Adding the blackout status to the legacy menu requires one http call for each event which will slow everything down so it hasn't been implemented.

**Comment by siuside** [comment]
Ok I just didn't know what was added via 19a222c to test. The event does give 403 in the logs via legacy menu.

**Comment by awaters1** [comment]
I made a commit af83f05baf3a8536b7222fe85a0ec0b174271882 to print the blackout url to the Kodi log file, can you go to that url and copy the contents to here?

**Comment by siuside** [comment]
{
	"TimeZone": "America/New_York",
	"EventId": "2811554",
	"E3BlackOut": "false",
	"LinearBlackOut": "true",
	"LinearSource": "null",
	"LinEventId": "2811554"
}



From the Kodi log

20:42:25 T:3640  NOTICE: ESPN3: args {'EVENT_PARENTAL_RATING': ['G'], 'EVENT_ID': ['2811554'], 'EVENT_NAME': ['#4 Miami (FL) vs. #14 North Carolina State (Pool Play Round) (ACC Baseball Championship)'], 'SESSION_URL': ['http://broadband.espn.go.com/espn3/auth/watchespn/startSession?&channel=espn3&simulcastAiringId=118925617'], 'NETWORK_NAME': ['espn3'], 'EVENT_GUID': ['espn3/#4 Miami (FL) vs. #14 North Carolina State (Pool Play Round) (ACC Baseball Championship)/2811554'], 'MODE': ['PLAY']}
20:42:25 T:3640  NOTICE: ESPN3: Blackout url http://broadband.espn.go.com/espn3/auth/watchespn/util/isUserBlackedOut?eventId=2811554

**Comment by awaters1** [comment]
Thank you for the report, for the ESPN3 channel I was checking E3BlackOut, but it looks like they use LinearBlackOut, I added this check in e3d791bb42c2c3916be77a92cf461f639319c8f4.

As a side question, what is the reason for using the legacy menu in the first place?  I am just wondering to see if you have any ideas to improve the AppleTV menu style.

**Comment by siuside** [comment]
Confirmed fixed 

`21:50:52 T:7660   ERROR: CAESinkDirectSound::CheckPlayStatus: Failed to play the DirectSound buffer: unknown
21:50:54 T:8768  NOTICE: ESPN3: args {'EVENT_PARENTAL_RATING': ['G'], 'EVENT_ID': ['2811590'], 'EVENT_NAME': ['#14 North Carolina State vs. Georgia Tech (Pool Play Round) (ACC Baseball Championship)'], 'SESSION_URL': ['http://broadband.espn.go.com/espn3/auth/watchespn/startSession?&channel=espn3&simulcastAiringId=118925620'], 'NETWORK_NAME': ['espn3'], 'EVENT_GUID': ['espn3/#14 North Carolina State vs. Georgia Tech (Pool Play Round) (ACC Baseball Championship)/2811590'], 'MODE': ['PLAY']}
21:50:54 T:8768  NOTICE: ESPN3: Blackout url http://broadband.espn.go.com/espn3/auth/watchespn/util/isUserBlackedOut?eventId=2811590`

From the blackout URL in browser

`{
	"TimeZone": "America/New_York",
	"EventId": "2811590",
	"E3BlackOut": "false",
	"LinearBlackOut": "true",
	"LinearSource": "null",
	"LinEventId": "2811590"
}`

and the nice popup upon selecting in the old style menu. 


Please close this if you are fine with it too?

There are reports that the lower powered boxes are preferring the Old Style menu for whatever reason. I personally prefer the AppleTV menu and will look for ideas to improve them. Pretty darn difficult though since you have almost perfected this ("Load more" , come on ;)). Seriously you have nailed it down pretty much, but I will look for ideas from other platforms too and see if it is doable for you. 

Really appreciate what you are doing here.
